import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"; //상단 바 import
import Hero from "@/components/Hero"; // Hero 섹션 import
import Subtitle from "@/components/Subtitle";
import TryItNow from "@/components/TryItNow";
import DropFileSection from "@/components/DropFileSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 상단 바 컴포넌트 추가  */}
        <Header /> 
        {/* Hero 섹션 추가  */}
        <Hero />
        {/* Subtitle(부제목) 추가 */}
        <Subtitle />
        {/* Try It Now 섹션 추가 */}
        <TryItNow />
        {/* 파일 드랍 영역 컴포넌트 추가  */}
        <DropFileSection />
        {children}
      </body>
    </html>
  );
}
